- name: Disable User Access Control UAC
  script: ../../common/files/disable-uac.bat

- name: Install DotNet Framework 4.6.1 
  win_chocolatey:
    name: dotnet4.6.1
    state: present

- name: Open port 1433 for remote connections to SQL Server
  win_firewall_rule:
      name: SQL Server Remote Connections
      localport: 1433
      action: allow
      direction: in
      protocol: tcp
      profiles: domain,private,public
      state: present
      enabled: yes

- name: Add Domain Users to Local Admins Group
  win_group_membership:
    name: Administrators
    members:
      - "{{ netbios }}\\SP_FARM"
      - "{{ netbios }}\\administrator"
    state: present
  register: domainusers

- name: Reboot Server so UAC changes take effect.
  win_reboot:
  when: domainusers.changed

- name: Download SQL Server ISO to C Drive
  win_get_url:
    url: http://www.techoverflow.com/SQLServer2016-x64-ENU.iso
    dest: c:\SQLServer2016-x64-ENU.iso
    force: no

- name: Copy SQL Server ConfigurationFile
  win_template:
    src: ../roles/Database/templates/ConfigurationFile.ini.j2
    dest: c:\ConfigurationFile.ini

- name: Mount SQL Server ISO Image
  win_disk_image:
    image_path: C:\SQLServer2016-x64-ENU.iso
    state: present
  register: disk_image_out

- name: Output debug info for path mount
  debug:
    msg: 'The path to SQL executable {{ disk_image_out.mount_path }}setup.exe'

- name: Run SQL Server unattended setup command using ConfigurationFile
  win_shell: "{{ disk_image_out.mount_path}}setup.exe /Q /ConfigurationFile=c:\\ConfigurationFile.ini"
  args:
    executable: cmd
