---
domain: "vmsak-dev.no"
netbios: "VMSAK-DEV"
dns_server: "192.168.2.18"

domain_vagrant_user: "{{ ansible_user }}@{{ domain }}"
domain_vagrant_password: Pass@word1!

domain_admin_user: "administrator@{{ domain }}"
domain_admin_password: Pass@word1!

sys_admin_account: "{{ netbios }}\\{{ ansible_user }}"


farm_password: "Pass@word1!"
services_password: "Pass@word1!"
portalapppool_password: "Pass@word1!"
search_service_password: "Pass@word1!"
search_content_password: "Pass@word1!"

ansible_user: vagrant
ansible_password: vagrant
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_operation_timeout_sec: 120
ansible_winrm_read_timeout_sec: 150

# The following is necessary for Python 2.7.9+ (or any older Python that has backported SSLContext, eg, Python 2.7.5 on RHEL7) when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore

#SharePoint related global variables
SharePointBitsPath: "c:\\SP\\2016\\SharePoint"
SharePointPrerequisitesPath: "c:\\SP\\2016\\prerequisiteinstallerfiles"

cloud_host: null
