- name: Ensure ADWS started
  win_service:
    name: ADWS
    state: started

- name: Create SharePoint Service Accounts
  win_domain_user:
    name: "{{ item }}"
    password: Pass@word1!
    state: present
    upn: "{{ item }}@{{ domain }}"
    domain_password: "Pass@word1!"
    domain_username: "Administrator@{{ domain }}"
  with_items:
    - SP_Admin
    - SP_CacheSuperReader
    - SP_CacheSuperUser
    - SP_Crawl
    - SP_ExcelUser
    - SP_Farm
    - SP_MySite
    - SP_PerfPointUser
    - SP_PortalAppPool
    - SP_ProfilesAppPool
    - SP_SearchContent
    - SP_SearchService
    - SP_Services
    - SP_VisioUser

- name: Add Vagrant Account to Domain Admins
  win_domain_user:
    name: vagrant
    firstname: Vagrant
    surname: Account
    upn: "{{ domain_vagrant_user }}"
    password: "{{ domain_vagrant_password }}"
    password_never_expires: yes
    account_locked: no
    domain_username: "{{ domain_admin_user }}"
    domain_password: "{{ domain_admin_password }}"
    state: present
    groups_action: add
    groups:
      - Domain Admins
