- name: Ensure ADWS started
  win_service:
    name: ADWS
    state: started

- name: Create SharePoint Service Accounts
  win_domain_user:
    name: "{{ item }}"
    password: Pass@word1!
    state: present
    upn: "{{ item }}@sposcar.local"
    domain_password: "Pass@word1!"
    domain_username: "Administrator@sposcar.local"
  with_items:
    - SP_Admin
    - SP_CacheSuperReader
    - SP_CacheSuperUser
    - SP_Crawl
    - SP_ExcelUser
    - SP_Farm
    - SP_MySite
    - SP_PerfPointUser
    - SP_PortalAppPool
    - SP_ProfilesAppPool
    - SP_SearchContent
    - SP_SearchService
    - SP_Services
    - SP_VisioUser

- name: Make SPOSCAR\vagrant Domain Admin
  win_domain_user:
    name: "vagrant"
    state: present
    upn: "vagrant@sposcar.local"
    domain_password: "Pass@word1!"
    domain_username: "Administrator@sposcar.local"
    groups:
      - "Domain Admins"
