- name: Ensure ADWS Services Running
  win_service:
    name: ADWS
    state: started

- name: Create SharePoint Service Accounts
  win_domain_user:
    name: "{{ item }}"
    password: "{{ services_password }}"
    state: present
    upn: "{{ item }}@{{ domain }}"
    domain_username: "{{ domain_admin_user }}"
    domain_password: "{{ domain_admin_password }}"
  with_items:
    - SP_Admin
    - SP_CacheSuperReader
    - SP_CacheSuperUser
    - SP_Crawl
    - SP_ExcelUser
    - SP_Farm
    - SP_MySite
    - SP_PerfPointUser
    - SP_PortalAppPool
    - SP_ProfilesAppPool
    - SP_SearchContent
    - SP_SearchService
    - SP_Services
    - SP_VisioUser
