- name: Ensure ADWS Services Running
  win_service:
    name: ADWS
    state: started
  tags:
    - all-environments

- name: Create SharePoint Service Accounts
  win_domain_user:
    name: "{{ item }}"
    password: "{{ services_password }}"
    state: present
    upn: "{{ item }}@{{ domain }}"
    domain_username: "{{ domain_admin_user }}"
    domain_password: "{{ domain_admin_password }}"
  with_items:
    - SP_Services
    - SP_PortalAppPool
    - SP_SearchService
    - SP_Admin
    - SP_CacheSuperReader
    - SP_CacheSuperUser
    - SP_Crawl
    - SP_Farm
    - SP_Vera
  tags:
    - local-only

# Azure doesn't allow use of Administrator account. Must use vagrant.
- name: Create SharePoint Service Accounts
  win_domain_user:
    name: "{{ item }}"
    password: "{{ services_password }}"
    state: present
    upn: "{{ item }}@{{ domain }}"
    domain_username: "{{ domain_vagrant_user }}"
    domain_password: "{{ domain_vagrant_password }}"
  with_items:
    - SP_Services
    - SP_PortalAppPool
    - SP_SearchService
    - SP_Admin
    - SP_CacheSuperReader
    - SP_CacheSuperUser
    - SP_Crawl
    - SP_Farm
    - SP_Vera

  tags:
    - azure-only