- name: Disable Password Security Policy
  win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: "0"
  tags:
    - all-environments

- name: Set Administrator Password
  win_user:
      name: Administrator
      password: "{{ domain_admin_password }}"
  tags:
    - all-environments

- name: Install Active Directory Feature
  win_feature:
    name: "{{ item }}"
    include_management_tools: yes
  with_items:
    - AD-domain-services
    - DNS
  tags:
    - all-environments    

- name: Ensure C:\Windows\NTDS Exists
  win_file:
    name: C:\Windows\NTDS
    state: directory
  tags:
    - all-environments    

- name: Create new Windows domain in a new forest
  win_domain:
    safe_mode_password: "{{ domain_admin_password }}"
    create_dns_delegation: no
    database_path: C:\Windows\NTDS
    domain_mode: Win2012R2
    dns_domain_name: "{{ domain }}"
    domain_netbios_name: "{{ netbios }}"
    forest_mode: Win2012R2
    install_dns: yes
    log_path: C:\Windows\NTDS
    sysvol_path: C:\Windows\SYSVOL
  register: dc_promotion
  tags:
    - all-environments  

- name: Reboot for AD changes to take effect
  win_reboot:
    post_reboot_delay: 720
  when: dc_promotion.reboot_required
  tags:
    - all-environments