

- name: Copy addServerToFarm PowerShell Script
  win_copy:
    src: ../../common/files/addServerToFarm.ps1
    dest: C:\SP\addServerToFarm.ps1
    force: false
  tags:
  - join-to-farm


- name: Trigger AutoSPInstaller (computer will restart and continue install)
  win_psexec:
    command: C:\SP\AutoSPInstaller\AutoSPInstallerLaunch.bat
    priority: high
    elevated: yes
    interactive: yes
    username: sposcar\vagrant
    password: Pass@word1!
    wait: no
  tags:
  - join-to-farm

- name: wait 300 seconds for port 2016 to become open on the host, don't start checking for 60 seconds
  win_wait_for:
    port: 2016
    host: {{cloud_host}}
    state: started
    delay: 60
  tags:
  - join-to-farm

- name: Join Server to existing SharePoint 2016 Farm
  win_psexec:
    command: powershell.exe Start-Process "$PSHOME\powershell.exe" -ArgumentList "'-NoExit -ExecutionPolicy Bypass  C:\SP\addServerToFarm.ps1 -DBServer SP2016SQLSERVER -DBName DEV_Config -PassPhrase Pass@word1! -SP2016 -ServerRole WebFrontEnd'"
    priority: high
    elevated: yes
    interactive: yes
    username: sposcar\vagrant
    password: Pass@word1!
    wait: no
  tags:
  - join-to-farm