- name: Setup DNS Server to point to DC
  win_dns_client:
    adapter_names: "Ethernet 2"
    ipv4_addresses: "192.168.2.19"
  tags:
    - join-to-domain

- name: Join Webserver to Domain Controller
  win_domain_membership:
      dns_domain_name: "{{domain}}"
      hostname: "SP2016WFE"
      domain_admin_user: "administrator@sposcar.local"
      domain_admin_password: "Pass@word1!"
      state: domain
  register: domain_state
  tags:
    - join-to-domain

- name: Reboot server after joining to Domain Server
  win_reboot:
  when: domain_state.reboot_required
  tags:
    - join-to-domain
