- name: Disable User Access Control UAC
  script: ../roles/internal/common/files/disable-uac.bat
  tags:
  - vagrant-environment

- name: Install .NET Framework 3.5 (its required for database install)
  win_feature:
    name: Net-Framework-Features
    state: present
    restart: yes
    include_sub_features: yes
    include_management_tools: yes
  tags:
  - vagrant-environment

# open up firewall port 1433 for SQL to accept incoming connections.
- name: Open port 1433 for remote connections to SQL Server
  win_firewall_rule:
      name: SQL Server Remote Connections
      localport: 1433
      action: allow
      direction: in
      protocol: tcp
      profiles: domain,private,public
      state: present
      enabled: yes
  tags:
  - all-environments

- name: Add Domain Users to Local Admins Group
  win_group_membership:
    name: Administrators
    members:
      - "{{ netbios }}\\SP_FARM"
      - "{{ netbios }}\\administrator"
    state: present
  register: domainusers

- name: Reboot Server so UAC changes take effect.
  win_reboot:
  when: domainusers.changed

- name: Download SQL Server ISO to root C:\
  win_get_url:
    url: http://download.microsoft.com/download/6/D/9/6D90C751-6FA3-4A78-A78E-D11E1C254700/SQLServer2014SP2-FullSlipstream-x64-ENU.iso
    dest: c:\SQLServer2014-x64-ENU.iso
    force: no
  tags:
  - vagrant-environment

- name: Copy SQL Server ConfigurationFile to C:\
  win_template:
    src: ../roles/internal/Database/templates/ConfigurationFile.ini.j2
    dest: c:\ConfigurationFile.ini
  tags:
  - vagrant-environment

- name: Mount SQL Server ISO Image
  win_disk_image:
    image_path: C:\SQLServer2014-x64-ENU.iso
    state: present
  register: disk_image_out
  tags:
  - vagrant-environment

- name: Output debug info for path mount
  debug:
    msg: 'The path to SQL executable {{ disk_image_out.mount_path }}setup.exe'
  tags:
  - vagrant-environment

#Run a command under a non-Powershell interpreter (cmd in this case)
- name: Run SQL Server unattended setup command using ConfigurationFile
  win_shell: D:\setup.exe /Q /ConfigurationFile=c:\ConfigurationFile.ini
  args:
    executable: cmd
  tags:
  - vagrant-environment
