- name: Setup DNS Server to point to DC
  win_dns_client:
    adapter_names: "Ethernet 2"
    ipv4_addresses: "{{ dns_server }}"
  tags:
    - join-to-domain
    - vagrant-environment

- name: Join Server to Domain Controller
  win_domain_membership:
      dns_domain_name: "{{ domain }}"
      hostname: "{{ cloud_host }}"
      domain_admin_user: "administrator@{{ domain }}"
      domain_admin_password: "{{ domain_admin_password }}"
      state: domain
  register: domain_state
  tags:
    - join-to-domain
    - all-environments

- name: Reboot server after joining to Domain Server
  win_reboot:
  when: domain_state.reboot_required
  tags:
    - join-to-domain
    - all-environments
