- name: Copy addServerToFarm PowerShell Script
  win_copy:
    src: ../../common/files/addServerToFarm.ps1
    dest: C:\SP\addServerToFarm.ps1
    force: false

- name: Join Server to SharePoint 2016 Farm
  win_psexec:
    command: powershell.exe Start-Process "$PSHOME\powershell.exe" -ArgumentList "'-NoExit -ExecutionPolicy Bypass  C:\SP\addServerToFarm.ps1 -DBServer SP2016SQLSERVER -DBName DEV_Config -PassPhrase Pass@word1! -SP2016 -ServerRole WebFrontEnd'"
    priority: high
    elevated: yes
    interactive: yes
    username: sposcar\vagrant
    password: Pass@word1!
    wait: no
